name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx3G # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx3G # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  push:
    branches: ['chunkboolean-constructors']

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2.3.5
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v13
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Lint code
      run: ./sbt check

  publishLocal:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2.3.5
      - name: Setup Scala and Java
        uses: olafurpg/setup-scala@v13
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check that building packages works
        run: ./sbt +publishLocal
